language: java

node_js:
  - 12

services:
  - docker

jdk: openjdk12

install: true

before_install:
  - pyenv install -s 3.8.1
  - pyenv local 3.8.1

script:
  - make installBlockDiag && make testBlockDiag
  - make buildServer
  - make buildDockerImages
  - npm install
  - make smokeTests
