language: java

node_js:
  - 12

services:
  - docker

jdk: openjdk12

install: true

script:
  - make installLocalDependencies
  - make buildServer
  - make buildDockerImages
  - npm install
  - make smokeTests
